### ISSUE TITLE
Index out of range cases crashing RStudio

### ISSUE THREAD

**Issue by luceydav** [girishji/re2#1]
Hi thanks for the package. Index out of range like in this example this crashes RStudio for me, so error handling would be a significant improvement if possible.

`x <- c(1:3)
re2_which(x, 4)`

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3  here_1.0.1      rprojroot_2.0.2 tools_4.0.3

**Comment by girishji** [comment]
Can you post the full crash message? I don't see it on my macbook running BigSur 13.3.1
```
> x <- c(1:3) 
> re2_which(x, 4)
Error in re2_which(x, 4) : 
  Expecting external pointer or string: [type=double].
> re2_which(x, '4')
integer(0)
```
It is behaving correctly. You are passing a number (4) when a regex pattern string is expected. It is throwing an exception as expected. Behavior is similar in stringr package.

**Comment by luceydav** [comment]
My mistake, apologies. I have been repeatedly crashing it somewhere in my code and thought that was it, but clearly not. If I find it, will revert. Apologies

**Comment by girishji** [comment]
No problem.
