### ISSUE TITLE
Any plans to implement re2_extract?

### ISSUE THREAD

**Issue by jjesusfilho** [girishji/re2#2]
Congratulations for the package, `re2_detect`  and `re2_replace` are much faster than their stringr and stringi counterparts.

I haven't seen a `re2_extract` similar to `str_extract` stringr. I can get the same results with `as.vector(re2_match(...))` or with `re2_extract_replace(text,"(pattern)", "\\1")`, but it turns out to be slower than `str_extract`. 

Also, the back references in the `re2_extract_replace` need double backslashes.

Finally, the development version didn't install on both Mac and Linux, only the cran version.

**Comment by girishji** [comment]
I'll look into re2_extract when I get some time.
Strange, dev version should install on Mac since I develop on Mac and it is the same code. I also tested on debian.
