### ISSUE TITLE
Suggestion for default argument R_PosInf in re2_split

### ISSUE THREAD

**Issue by eddelbuettel** [girishji/re2#3]
I noticed that `Rcpp::compileAttributes()` isn't happy with the use of the (R-only) constant R_PosInf. One possibility (since Rcpp 1.0.8) is to add a default signature _at the R side_.  This can obtained via the diff below.  Happy to send a PR if you prefer.

```diff
diff --git a/src/re2_split.cpp b/src/re2_split.cpp
index 4d6928d..ffa6547 100644
--- a/src/re2_split.cpp
+++ b/src/re2_split.cpp
@@ -70,9 +70,8 @@ struct DoSplit : re2::DoMatchIntf {
 //'   \link{re2_syntax} for regular expression syntax, and
 //'   \code{\link{re2_match}} to extract matched groups.
 //'
-// [[Rcpp::export]]
-SEXP re2_split(StringVector string, SEXP pattern, bool simplify = false,
-               double n = R_PosInf) {
+// [[Rcpp::export(signature={string, pattern, simplify=FALSE, n=Inf})]]
+SEXP re2_split(StringVector string, SEXP pattern, bool simplify, double n) {
   if (simplify) {
     List lst = re2_split(string, pattern, false, n);
     int maxcols = 0;
```

**Comment by girishji** [comment]
I added above change and verified. I submitted to CRAN. Thanks for taking care of this issue in Rcpp 1.0.8!

**Comment by eddelbuettel** [comment]
Yes it was a nice contribution from another Rcpp user that is helpful (if underdocumented, need to add a section to the corresponding vignette).    Glad to see `re2` already back on CRAN (per my CRANberries hourly scanning).
